pages
moreExamples
	^HelpTopic 
		title: 'More Examples'
		contents: 'If you browse the Spec-Examples package you will find a lot more examples that will help you understand Spec a little more.
		
ApplicationWithToolbar new openWithSpec

CheckBoxExample new openWithSpec

ClassMethodBrowser new openWithSpec

DropListExample new openWithSpec

DynamicWidgetChange new openWithSpec

ListSelectionPresenter new openWithSpec

MethodBrowser new openWithSpec

ModelList new openWithSpec

ProtocolBrowser new openWithSpec

ProtocolList new openWithSpec

ProtocolViewer new openWithSpec

RadioButtonGroupExample new openWithSpec

ScrollSyncExample new openWithSpec

TabsExample new openWithSpec

TextFieldExample new openWithSpec'