"
This class offers a number of extra icons that work with the Glamorous Theme.
"
Class {
	#name : #GLMUIThemeExtraIcons,
	#superclass : #Model,
	#classInstVars : [
		'icons'
	],
	#category : #'Glamour-Morphic-Theme'
}

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousAccept [
	^ self iconNamed: #glamorousAccept
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousAdd [
	^ self iconNamed: #glamorousAdd
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousAlarm [
	^ self iconNamed: #glamorousAlarm
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousBookmark [
	^ self iconNamed: #glamorousBookmark
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousBrowse [
	^ self iconNamed: #glamorousBrowse
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousBug [
	^ self iconNamed: #glamorousBug
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousCancel [
	^ self iconNamed: #glamorousCancel
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousClose [
	^ self iconNamed: #glamorousClose
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousDown [
	^ self iconNamed: #glamorousDown
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousDropDown [
	^ self iconNamed: #glamorousDropDown
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousEdit [
	^ self iconNamed: #glamorousEdit
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousExample [
	^ self iconNamed: #glamorousExample
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousFolder [
	^ self iconNamed: #glamorousFolder
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousGo [
	^ self iconNamed: #glamorousGo
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousGrayCircle [
	^ self iconNamed: #glamorousGrayCircle
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousGrayCircleEmpty [
	^ self iconNamed: #glamorousGrayCircleEmpty
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousGreenCircle [
	^ self iconNamed: #glamorousGreenCircle
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousHelp [
	^ self iconNamed: #glamorousHelp
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousInspect [
	^ self iconNamed: #glamorousInspect
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousInto [
	^ self iconNamed: #glamorousInto
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousLargeGrayCircleEmphasized [
	^ self iconNamed: #glamorousLargeGrayCircleEmphasized
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousLeft [
	^ self iconNamed: #glamorousLeft
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousLeftSide [
	^ self iconNamed: #glamorousLeftSide
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousMore [
	^ self iconNamed: #glamorousMore
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousOpen [
	^ self iconNamed: #glamorousOpen
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousOpenFromUrl [
	^ self iconNamed: #glamorousOpenFromUrl
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousOver [
	^ self iconNamed: #glamorousOver
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousPlay [
	^ self iconNamed: #glamorousPlay
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousRedCircle [
	^ self iconNamed: #glamorousRedCircle
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousRedo [
	^ self iconNamed: #glamorousRedo
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousRefresh [
	^ self iconNamed: #glamorousRefresh
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousRemove [
	^ self iconNamed: #glamorousRemove
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousRestart [
	^ self iconNamed: #glamorousRestart
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousRight [
	^ self iconNamed: #glamorousRight
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousRightSide [
	^ self iconNamed: #glamorousRightSide
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousSave [
	^ self iconNamed: #glamorousSave
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousSaveToUrl [
	^ self iconNamed: #glamorousSaveToUrl
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousSearch [
	^ self iconNamed: #glamorousSearch
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousSpawn [
	^ self iconNamed: #glamorousSpawn
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousThrough [
	^ self iconNamed: #glamorousThrough
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousTrash [
	^ self iconNamed: #glamorousTrash
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousUndo [
	^ self iconNamed: #glamorousUndo
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousUp [
	^ self iconNamed: #glamorousUp
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousZoomIn [
	^ self iconNamed: #glamorousZoomIn
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousZoomOut [
	^ self iconNamed: #glamorousZoomOut
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousZoomToFit [
	^ self iconNamed: #glamorousZoomToFit
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamourousNextFailure [
	^ self iconNamed: #glamourousNextFailure
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamourousNextParser [
	^ self iconNamed: #glamourousNextParser
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamourousNextProduction [
	^ self iconNamed: #glamourousNextProduction
]

{ #category : #utils }
GLMUIThemeExtraIcons class >> icons [
	^ icons ifNil: [icons := Dictionary new] 
]

{ #category : #utils }
GLMUIThemeExtraIcons class >> resetIcons [
	icons := nil
]
