public
commentForCurrentUpdate
 ^ '19514 ConfigurationOfFuel has no latest FuelTests version
	https://pharo.fogbugz.com/f/cases/19514

19421 Failing test: WeakAnnouncerTest>>#testNoDeadWeakSubscriptions
	https://pharo.fogbugz.com/f/cases/19421

19512 References to Tab -> should be TabMorph
	https://pharo.fogbugz.com/f/cases/19512

18729 DNU on showing menu in CriticBrowser (code pane)
	https://pharo.fogbugz.com/f/cases/18729'