# Number of reviews required to mark the pull request as valid
reviewsUntilReady: 1

# Number of changes in the pull request to start enforcing the reviewsUntilReady rule. For Pharo changes are often very small
changesThreshold: 1

# Message to display when the commit status passes
readyMessage: 'No pending reviews'

# Message to display when the commit status fails
notReadyMessage: 'Pending review approvals'

# Status to set the commit to when waiting for reviews
# 'failure, error, and pending' are the suggested options
notReadyState: 'pending'
