Class {
	#name : #ClyAbstractMethodGroupProviderTest,
	#superclass : #ClyMethodGroupProviderTestCase,
	#category : #'Calypso-SystemPlugins-InheritanceAnalysis-Queries-Tests'
}

{ #category : #running }
ClyAbstractMethodGroupProviderTest >> classSampleWhichHasGroup [

	^ClyAbstractClassExample
]

{ #category : #running }
ClyAbstractMethodGroupProviderTest >> groupProviderClass [
	^ClyAbstractMethodGroupProvider 
]
