"
I am a package part of the Spec 2 project.

Spec is a framework in Pharo for describing user interfaces. It allows for the construction of a wide variety of UIs; from small windows with a few but- tons up to complex tools like a debugger. Indeed, multiple tools in Pharo are written in Spec, e.g., Iceberg, Change Sorter, Critics Browser, and the Pharo debugger.

I contain the layouts used by presenters to position their elements.
"
Class {
	#name : #ManifestSpec2Layout,
	#superclass : #PackageManifest,
	#category : #'Spec2-Layout-Manifest'
}
