"
I am a package part of the Spec 2 project.

Spec is a framework in Pharo for describing user interfaces. It allows for the construction of a wide variety of UIs; from small windows with a few but- tons up to complex tools like a debugger. Indeed, multiple tools in Pharo are written in Spec, e.g., Iceberg, Change Sorter, Critics Browser, and the Pharo debugger.

I contain a layer of compatibility for the Commander 2 project.

Commander 2 is a project to create commands following the Command design pattern. With the compatibility layer you can add icons or shortcuts to your commands and integrate them easily in your presenters.
"
Class {
	#name : #ManifestSpec2Commander2,
	#superclass : #PackageManifest,
	#category : #'Spec2-Commander2-Manifest'
}
