SystemOrganization addCategory: #'Morphic-Base'!
SystemOrganization addCategory: 'Morphic-Base-Basic'!
SystemOrganization addCategory: 'Morphic-Base-Borders'!
SystemOrganization addCategory: 'Morphic-Base-Events'!
SystemOrganization addCategory: 'Morphic-Base-Kernel'!
SystemOrganization addCategory: 'Morphic-Base-Layouts'!
SystemOrganization addCategory: 'Morphic-Base-Menus'!
SystemOrganization addCategory: 'Morphic-Base-ProgressBar'!
SystemOrganization addCategory: 'Morphic-Base-Text Support'!
SystemOrganization addCategory: 'Morphic-Base-Widgets'!
