"
This class is an attempt to see how we can turn extractMethodTestData like method into a static model (e.g., plain simple class definition) 
and a rb model creation. This RB model will be will only in the setup and the setUp should not require to compile code.
"
Class {
	#name : #RBStaticModelCreationTest,
	#superclass : #RBAbstractEnvTestCase,
	#category : #'Refactoring2-Transformations-Tests-Test'
}
