"
I store metadata for this package. These meta data are used by other tools such as the SmalllintManifestChecker and the critics Browser
"
Class {
	#name : #ManifestIcebergPluginGitHub,
	#superclass : #PackageManifest,
	#category : #'Iceberg-Plugin-GitHub-Manifest'
}

{ #category : #'meta-data' }
ManifestIcebergPluginGitHub class >> description [ ^ 'I contains a plugin to ease the integration of Iceberg with GitHub''s services.

It provides, for example, the possibility to manage pull requests. '
]
